services:
  calc_app:
    image: ${IMAGE_REPO}:${IMAGE_TAG}
    ports:
      - target: 8710
        published: 8710
        protocol: tcp
        mode: ingress
    environment:
      - HOST=0.0.0.0
      - PORT=8710
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
        reservations:
          cpus: "0.10"
          memory: "128M"
