version: "3.8"

services:
  calc_app:
    image: ${IMAGE_REPO}:${IMAGE_TAG} # resolved by the workflow's env
    ports:
      - "8710:8710"
    environment:
      - HOST="0.0.0.0"
      - PORT="8710"
    deploy:
      resources:
        limits:
          cpus: "0.50" # must be strings in Swarm
          memory: "512M"
        reservations:
          cpus: "0.10"
          memory: "128M"
