name: Deploy to Server (Docker Swarm)

on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Deployment Environment
              env:
                  APP_PATH: /opt/calc_app
              run: |
                  echo "Tworzenie/Czyszczenie katalogu docelowego: ${APP_PATH}"

                  mkdir -p ${APP_PATH}

                  # JEDNOKROTNIE ZAPEWNIJ WŁASNOŚĆ (jeśli to konieczne)
                  # sudo chown -R gitactions:gitactions /opt/calc_app 

                  # Używamy rsync do synchronizacji i WYKLUCZENIA KATALOGU GIT (.git)
                  # Wykluczenie .git jest kluczowe dla uniknięcia błędów uprawnień
                  rsync -av --delete --exclude='.git' ${{ github.workspace }}/ ${APP_PATH}/

                  echo "### Weryfikacja: Zawartość katalogu docelowego (${APP_PATH}) ###"
                  ls -la ${APP_PATH}

            - name: Build and Deploy to Docker Swarm (Final)
              env:
                  APP_NAME: loan-calc-app
                  STACK_NAME: calc_stack
                  APP_PATH: /opt/calc_app
              run: |
                  # Usuń stary tag obrazu
                  docker rmi ${APP_NAME}:latest || true

                  echo "Budowanie nowego obrazu: ${APP_NAME}:latest, używając kontekstu: ${APP_PATH}"

                  # JAWNIE USTAWIAMY KONTEKST BUDOWANIA, co jest niezawodne
                  docker build -t ${APP_NAME}:latest ${APP_PATH}

                  # WDRAŻANIE DO SWARM
                  echo "Wdrażanie do Docker Swarm pod stosem ${STACK_NAME}..."
                  docker stack deploy -c ${APP_PATH}/docker-compose.yml ${STACK_NAME}

                  # --- Weryfikacja ---
                  echo "Sprawdzanie stanu usługi Swarm."
                  docker service ls | grep ${STACK_NAME}
