name: Deploy to Server

on:
    push:
        branches:
            - master

jobs:
    deploy:
        # Zmieniamy, aby użyć naszego lokalnego runnera:
        runs-on: self-hosted # Lub runs-on: [self-hosted, linux, x64]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build and Restart Docker Container
              env:
                  APP_NAME: loan-calc-app
                  CONTAINER_NAME: my-calc-container
                  APP_PATH: /opt/calc_app
              run: |
                  # 1. Przejdź do katalogu aplikacji (na serwerze)
                  cd ${APP_PATH}

                  # 2. Zatrzymaj i usuń istniejący kontener
                  docker stop ${CONTAINER_NAME} || true
                  docker rm ${CONTAINER_NAME} || true

                  # 3. Usuń stary obraz, aby mieć pewność, że zbuduje się nowy
                  docker rmi ${APP_NAME} || true

                  # 4. Zbuduj nowy obraz Dockera z plików pobranych przez runnera
                  docker build -t ${APP_NAME} .

                  # 5. Uruchom nowy kontener z autostartem
                  docker run -d -p 8710:8710 --name ${CONTAINER_NAME} --restart unless-stopped ${APP_NAME}
